spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dopimex_partner
    username: root
    password: 15102017
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8000/eureka
